### PR TITLE
PR for moving REST Device Service out of holding

### PR DESCRIPTION
**Pull request by lenny-intel**
This dummy PR is for capturing comment on moving the REST Device Service out of holding.

Please review the code/docs/configs on the master branch and add your comments to this PR.
https://github.com/edgexfoundry-holding/device-rest-go/tree/master

### CODE REVIEW

**Comment by hahattan** [comment]
example endpoints in Testing/Simulation section should be http://localhost:59995/api/v1/resource/{deviceName}/{resourceName}

**Comment by lenny-intel** [comment]
@hahattan , Good Catch! Thx

**Comment by tonyespy** [comment]
First, there's some misunderstanding about the PR for moving a repository from the edgex-holding organization to the edgexfoundry organization. Using a PR gives us to things:

 * it allows us to record comments and actual approval from one (or ideally more) project developers. Ideally once moved, the -holding repository is archived, but this review PR (and the reviewers's approval and comments are still available for historic purposes.

 * it allows the submitter to provide some basic information to the reviewers as described by our current [process for moving a new device service out of holding](https://wiki.edgexfoundry.org/display/FA/Process+for+new+Device+Services). Think of this like a PR description that you'd like someone to return. The information asked for every new service includes:
    * What types of device are supported.
    * What protocol features are supported / likely to be supported in future.
    * What limitations does the existing implementation have.
    * What hardware and software has it been tested against.
    * What release of EdgeX is this intended for?

 * I also don't think this PR should be used to propose changes to the service either (i.e. there should be no commits associated with this PR).

**Comment by iain-anderson** [comment]
I've assigned 49986 as the default port for device-rest

**Comment by lenny-intel** [comment]
@tonyespy, see my responses below.

> Here's my review, but I'm not explicitly approving until we have agreement on how and what needs to be resolved (and whether we just open issues for each). Without further adieu, here are my comments:
> 
> 1. The first commit "Create README.md" lacks signoff

_**Not sure how this happened. Strange that it is verified, but not signed-off ... Not sure how to fix this since unable to use rebase due to this being the very first commit.**_

> 2. The code seems to be pretty light with respect to comments... [nit]

_**I feel the code is written in a way that it can be understood without a bunch of comments.**_

> 3. **README.md**
> 
> * _Runtime Requisite(s)_ should be _Runtime Prequisites_, although I question why you even need to include this, as every device service requires both Core Data and Core Metadata to function currently.

_**Ok, on the renaming. It is still useful for someone not as familiar with the project.**_

> * **REST Endpoints**
>   
>   * devices are not defined in device profiles and the configuration.toml. A device profile describes a class of devices. Also device is a standard model and can be added via REST calls to Core Metadata, via a go SDK function/method, or via configuration.

**How about something like: `_refers to the device name of the device profile to use. `**

>   * I would suggest the following text for resourceName: _refers to the device resource defined in the device profile associated with the given deviceName_.

_**Ok**_

>   * I thought we were trying to move away from sending or receiving just strings (or other types) and wanted to move towards have requests and responses. The endpoint here seems to just accept a string (any length restriction) or a binary blob. If we're not going to pass a request object, then I think at minimum we should require a Content-Header (e.g. image/jpeg).

**There isn't a know request object. What would we do with the Content-Header if we required it. The main usage of this DS in our use cases is to send in JSON strings.**

> * **Configuration**
>   
>   * This says you can send JSON data, binary data or number (numeric?) data. This seems confusing because the previous section says you can send text or binary data.

_**In the note just above `Configuration` it explains that `The text is casted to the specific type of the specified device resource once it passes type validation.`**_

>   * Why does `DeviceList.Protocols.other` need to specified?

_**Because SDK is requiring something under `DeviceList.Protocols`. Gives an error if I don't have it.**_

> * **Device Profile**
>   
>   * do these device profiles work w/out Core Commands defined? I seem to recall a requirement that device profiles always include this section?

**_Yes. DeviceCommands is required, but CoreCommands is not._**

>   * In sample-binary, how come the PostBinary resource command only defines a "get" operation? I thought reads weren't supported?

_**This is how DeviceCommands work. It is `getting` the data from the device. It throw me off at first also. Same in the other device profiles.**_ 

> * **Testing / Simulation** - some sample POST bodies would be helpful in this section.

_**ok**_

> * **Commanding** - I would move this to the top, and drop the word "Commanding". Instead just describe the service as only supporting asynchronous readings, and state that the service doesn't support any commands (read or write).

_**ok**_

> 
> 1. **Attribution.txt** doesn't seem to match up with the 3rd party packages used by this device service. Also while looking at this, it appears that the sample Attribution.txt in device-sdk-go hasn't been kept up to date, and I'm not sure how a device service developer is supposed to know they're required to ship this file with any binary distribution of a device service.

_**I reran the ./bin/test-attribution-txt.sh script and it doesn't identify anything missing. What to you see wrong? As for the SDK, there is an issue I created for this (https://github.com/edgexfoundry/device-sdk-go/issues/399) which has been addressed.**_

> 2. **Dockerfile** - doesn't include the **LICENSE** or **Attribution.txt**

_**Licence is in header and a lable on image:**
`LABEL license='SPDX-License-Identifier: Apache-2.0' \
  copyright='Copyright (c) 2019: Intel'`_
What are you expecting for **Attribution.txt**?

> 3. **cmd/main.go** - use of bootstrap precludes usage of `SetOverwriteConf` method

_**This is how latest device-mqtt's & device-virtual's main work. How should it work? @cloudxxx8 ??**_

> 4. **driver/restdriver.go**
>    
>    * code lines are long, why wrap the godoc?

_**I have NP wrapping code. Wrapped comments for readability.**_

> 5. **driver/resthandler_test.go**
>    
>    * no copyright / license header!

_**Yep, missed that one.**_

**Comment by lenny-intel** [comment]
> First, there's some misunderstanding about the PR for moving a repository from the edgex-holding organization to the edgexfoundry organization. Using a PR gives us to things:
> 
> * it allows us to record comments and actual approval from one (or ideally more) project developers. Ideally once moved, the -holding repository is archived, but this review PR (and the reviewers's approval and comments are still available for historic purposes.
> * it allows the submitter to provide some basic information to the reviewers as described by our current [process for moving a new device service out of holding](https://wiki.edgexfoundry.org/display/FA/Process+for+new+Device+Services). Think of this like a PR description that you'd like someone to return. The information asked for every new service includes:
>   
>   * What types of device are supported.
>   * What protocol features are supported / likely to be supported in future.
>   * What limitations does the existing implementation have.
>   * What hardware and software has it been tested against.
>   * What release of EdgeX is this intended for?
> * I also don't think this PR should be used to propose changes to the service either (i.e. there should be no commits associated with this PR).

@tonyespy , Are you expecting separate PR(s) for addressing this PR's feedback? That seems a bit strange and disconnected to me... Also, current process is to move the repos from holding, not archive them. Thus once they are in the main org, the history from holding is retained.

**Comment by tonyespy** [comment]
> @tonyespy, see my responses below.
> 
> > Here's my review, but I'm not explicitly approving until we have agreement on how and what needs to be resolved (and whether we just open issues for each). Without further adieu, here are my comments:
> > 
> > 1. The first commit "Create README.md" lacks signoff
> 
> _**Not sure how this happened. Strange that it is verified, but not signed-off ... Not sure how to fix this since unable to use rebase due to this being the very first commit.**_

`$ git rebase -i --root`

> > 1. The code seems to be pretty light with respect to comments... [nit]
> 
> _**I feel the code is written in a way that it can be understood without a bunch of comments.**_

I think there are some parts of the code that aren't entirely obvious, but I'm not going to hold up the PR for this.

> > * **REST Endpoints**
> >   
> >   * devices are not defined in device profiles and the configuration.toml. A device profile describes a class of devices. Also device is a standard model and can be added via REST calls to Core Metadata, via a go SDK function/method, or via configuration.
> 
> **How about something like: `_refers to the device name of the device profile to use. `**

That's still not quite right. In this case, `deviceName` simply refers to the device managed by this device service.

> > * I thought we were trying to move away from sending or receiving just strings (or other types) and wanted to move towards have requests and responses. The endpoint here seems to just accept a string (any length restriction) or a binary blob. If we're not going to pass a request object, then I think at minimum we should require a Content-Header (e.g. image/jpeg).
> 
> **There isn't a know request object. What would we do with the Content-Header if we required it. The main usage of this DS in our use cases is to send in JSON strings.**

Sure, but you're also providing binary support, and I think having the incoming endpoint accept an arbitrary binary payload as a POST request without a Content-Header isn't especially wise (i.e. and would seem ripe for a targeted attack). As for what we could do with it? You could ensure that it matches the **MediaType** of the given device resource, and if not return an error.

For string POST requests, the Content-Header should probably be required to be set as "text/plain".

> > * **Configuration**
> >   
> >   * This says you can send JSON data, binary data or number (numeric?) data. This seems confusing because the previous section says you can send text or binary data.
> 
> _**In the note just above `Configuration` it explains that `The text is casted to the specific type of the specified device resource once it passes type validation.`**_

I'm just saying there really are two data types supported for import using this endpoint, string and binary, with the former having support for casting to the native non-binary data types supported by EdgeX. In your configuration sample-json and sample-numbers, both are examples that support an POST specifying a string, which is cast to one of the native types, so that's why having three profiles is a slightly bit confusing. That said I'm willing to punt on this one. If you do keep them, I still would suggest re-naming sample-json to sample-string.

> > * Why does `DeviceList.Protocols.other` need to specified?
> 
> _**Because SDK is requiring something under `DeviceList.Protocols`. Gives an error if I don't have it.**_

Ugh, OK. Does this end up generating the real string "other" in the ProtocolProperties map? If so, seems a bit superfluous (i.e. it's not really used for anything).
 
> > * **Device Profile**
> >   
> >   * do these device profiles work w/out Core Commands defined? I seem to recall a requirement that device profiles always include this section?
> 
> **_Yes. DeviceCommands is required, but CoreCommands is not._**

OK

> > * In sample-binary, how come the PostBinary resource command only defines a "get" operation? I thought reads weren't supported?
> 
> _**This is how DeviceCommands work. It is `getting` the data from the device. It throw me off at first also. Same in the other device profiles.**_

Well you could re-name the device command to GetBinary. But when a new incoming value is pushed to the service via REST, the deviceResource name is what gets inserted into the new Reading right? In this case, the fact that there's a corresponding device command is not really accomplishing anything here... I know @iain-anderson had proposed some additional device profile simplifications, but I'm not sure we've committed to do these for Geneva. Let's bring this up at next week's WG meeting. 

> > 1. **Attribution.txt** doesn't seem to match up with the 3rd party packages used by this device service. Also while looking at this, it appears that the sample Attribution.txt in device-sdk-go hasn't been kept up to date, and I'm not sure how a device service developer is supposed to know they're required to ship this file with any binary distribution of a device service.
> 
> _**I reran the ./bin/test-attribution-txt.sh script and it doesn't identify anything missing. What to you see wrong? As for the SDK, there is an issue I created for this ([edgexfoundry/device-sdk-go#399](https://github.com/edgexfoundry/device-sdk-go/issues/399)) which has been addressed.**_

I have to admit, I wasn't aware of the existence of test-attribution-txt.sh, so I didn't realize this file was auto-generated and in fact recursively walked all of the dependencies. I'll discuss @anonymouse64, as maybe it would be a good idea to add a "# auto-generated by test-attribution-txt.sh; DO NOT EDIT to the top of each auto-generated Attribution.txt file.

> > 1. **Dockerfile** - doesn't include the **LICENSE** or **Attribution.txt**
> 
> _**Licence is in header and a lable on image:** `LABEL license='SPDX-License-Identifier: Apache-2.0' \ copyright='Copyright (c) 2019: Intel'`_
> What are you expecting for **Attribution.txt**?

First, many license still require the license text to be included in any binary distribution, so while you've identified the docker image as containing software licensed under Apache 2.0, you haven't included the license file itself. This may not be required by Apache 2.0, but in general it's good practice. In the snaps, we always copy Attribution.txt and LICENSE to /usr/share/doc/\<thing\>/ similar to the way debian packages work.

> > 1. **cmd/main.go** - use of bootstrap precludes usage of `SetOverwriteConf` method
> 
> _**This is how latest device-mqtt's & device-virtual's main work. How should it work? @cloudxxx8 ??**_

The `SetOverwriteConf` was just recently merged into device-sdk-go, and released as 1.1.1. For Geneva, in theory we have the freedom to break the API and will add an overwrite-conf parameter to `NewService` and maybe even `startup.Bootstrap`. @cloudxxx8 is there an issue to track this change for Geneva.

> > 1. **driver/restdriver.go**
> >    
> >    * code lines are long, why wrap the godoc?
> 
> _**I have NP wrapping code. Wrapped comments for readability.**_

OK, looks a bit odd, which is why I mentioned it. It passes gofmt, so let's leave as is.

**Comment by tonyespy** [comment]
> > First, there's some misunderstanding about the PR for moving a repository from the edgex-holding organization to the edgexfoundry organization. Using a PR gives us to things:
> > 
> > * it allows us to record comments and actual approval from one (or ideally more) project developers. Ideally once moved, the -holding repository is archived, but this review PR (and the reviewers's approval and comments are still available for historic purposes.
> > * it allows the submitter to provide some basic information to the reviewers as described by our current [process for moving a new device service out of holding](https://wiki.edgexfoundry.org/display/FA/Process+for+new+Device+Services). Think of this like a PR description that you'd like someone to return. The information asked for every new service includes:
> >   
> >   * What types of device are supported.
> >   * What protocol features are supported / likely to be supported in future.
> >   * What limitations does the existing implementation have.
> >   * What hardware and software has it been tested against.
> >   * What release of EdgeX is this intended for?
> > * I also don't think this PR should be used to propose changes to the service either (i.e. there should be no commits associated with this PR).
> 
> @tonyespy , Are you expecting separate PR(s) for addressing this PR's feedback? 

No, I think the review PR should have a single empty commit which just says something like:

Move repo to github.com/edgexfoundry

If you address comments in the PR review, just commit them to master, push them directly, then re-base this PR (which is easy as there no changes to the tree) and force-push it.

> That seems a bit strange and disconnected to me... Also, current process is to move the repos from holding, not archive them. Thus once they are in the main org, the history from holding is retained.

Ah OK, I wasn't *exactly* sure that's what happened. If so, then it's ideal as the empty move commit will exist, and the PR history will be preserved too.

**Pull request closed without merging**
